export const FETCH_DELIVERYPOINTS_REQUEST = "FETCH_DELIVERYPOINTS_REQUEST";
export const FETCH_DELIVERYPOINTS_SUCCESS = "FETCH_DELIVERYPOINTS_SUCCESS";
export const FETCH_DELIVERYPOINTS_FAILURE = "FETCH_DELIVERYPOINTS_FAILURE";